version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: always
    image: vnspc/nginx:1.25
    ports:
      - ${NGINX_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    volumes: &appvolumes
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - ./src:/var/www:cached
      - sock-data:/sock
      - ssl-data:/etc/nginx/certs
    depends_on:
      - golang
    extra_hosts: &appextrahosts
      - "*:172.17.0.1"
    networks:
      - network-bridge

  golang:
    container_name: golang
    restart: always
    image: vnspc/golang:1.22
    volumes: *appvolumes
    extra_hosts: *appextrahosts
    networks:
      - network-bridge

  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.3
    ports:
      - ${MYSQL_DB_PORT:-3306}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    networks:
      - network-bridge

volumes:
  mysql-data:
  sock-data:
  ssl-data:

networks:
  network-bridge:
    driver: bridge
    name: network-bridge
