FROM golang:1.22-alpine
LABEL maintainer="Son Tran Thanh <286.trants@gmail.com>"

# Set the current working directory inside the container
WORKDIR /var/www

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
ENTRYPOINT ["air"]
