name: Docker PHP 7.0 Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'images/php/7.0/**'

jobs:
  docker-build-php-70:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_TOKEN }}

      - name: Builds and pushes Docker image
        uses: docker/build-push-action@v5
        with:
          context: images/php/7.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_PHP_IMAGE }}:7.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
